// Mocks generated by Mockito 5.4.5 from annotations
// in isomorph_iq/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i18;
import 'dart:ui' as _i22;

import 'package:flutter/material.dart' as _i19;
import 'package:isomorph_iq/models/app_connections_model.dart' as _i9;
import 'package:isomorph_iq/models/crypto_news_model.dart' as _i14;
import 'package:isomorph_iq/models/fetch_user_personality.dart' as _i15;
import 'package:isomorph_iq/models/generate_tweet.dart' as _i11;
import 'package:isomorph_iq/models/google_sign.dart' as _i10;
import 'package:isomorph_iq/models/leaderboard_model.dart' as _i7;
import 'package:isomorph_iq/models/post_model.dart' as _i5;
import 'package:isomorph_iq/models/profile_model.dart' as _i4;
import 'package:isomorph_iq/models/save_generated_tweet.dart' as _i12;
import 'package:isomorph_iq/models/tweets_model.dart' as _i13;
import 'package:isomorph_iq/models/upsert_user_personality.dart' as _i16;
import 'package:isomorph_iq/models/user_points.dart' as _i6;
import 'package:isomorph_iq/models/user_rank_model.dart' as _i8;
import 'package:isomorph_iq/services/api_client.dart' as _i3;
import 'package:isomorph_iq/services/api_service.dart' as _i25;
import 'package:isomorph_iq/services/authorization_service.dart' as _i27;
import 'package:isomorph_iq/services/hive_service.dart' as _i26;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stacked/stacked.dart' as _i2;
import 'package:stacked_services/src/bottom_sheet/bottom_sheet_service.dart'
    as _i20;
import 'package:stacked_services/src/dialog/dialog_service.dart' as _i23;
import 'package:stacked_services/src/models/overlay_request.dart' as _i24;
import 'package:stacked_services/src/models/overlay_response.dart' as _i21;
import 'package:stacked_services/src/navigation/router_service.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRootStackRouter_0 extends _i1.SmartFake
    implements _i2.RootStackRouter {
  _FakeRootStackRouter_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouteData_1 extends _i1.SmartFake implements _i2.RouteData {
  _FakeRouteData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRoutingController_2 extends _i1.SmartFake
    implements _i2.RoutingController {
  _FakeRoutingController_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiClient_3 extends _i1.SmartFake implements _i3.ApiClient {
  _FakeApiClient_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfile_4 extends _i1.SmartFake implements _i4.UserProfile {
  _FakeUserProfile_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostResponse_5 extends _i1.SmartFake implements _i5.PostResponse {
  _FakePostResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserPoints_6 extends _i1.SmartFake implements _i6.UserPoints {
  _FakeUserPoints_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLeaderboard_7 extends _i1.SmartFake implements _i7.Leaderboard {
  _FakeLeaderboard_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserRank_8 extends _i1.SmartFake implements _i8.UserRank {
  _FakeUserRank_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppConnections_9 extends _i1.SmartFake
    implements _i9.AppConnections {
  _FakeAppConnections_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignAuth_10 extends _i1.SmartFake implements _i10.SignAuth {
  _FakeSignAuth_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerateTweet_11 extends _i1.SmartFake
    implements _i11.GenerateTweet {
  _FakeGenerateTweet_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveGeneratedTweet_12 extends _i1.SmartFake
    implements _i12.SaveGeneratedTweet {
  _FakeSaveGeneratedTweet_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTweets_13 extends _i1.SmartFake implements _i13.Tweets {
  _FakeTweets_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCryptoNews_14 extends _i1.SmartFake implements _i14.CryptoNews {
  _FakeCryptoNews_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFetchUserPersonality_15 extends _i1.SmartFake
    implements _i15.FetchUserPersonality {
  _FakeFetchUserPersonality_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpsertUserPersonality_16 extends _i1.SmartFake
    implements _i16.UpsertUserPersonality {
  _FakeUpsertUserPersonality_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RouterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouterService extends _i1.Mock implements _i17.RouterService {
  @override
  _i2.RootStackRouter get router => (super.noSuchMethod(
        Invocation.getter(#router),
        returnValue: _FakeRootStackRouter_0(
          this,
          Invocation.getter(#router),
        ),
        returnValueForMissingStub: _FakeRootStackRouter_0(
          this,
          Invocation.getter(#router),
        ),
      ) as _i2.RootStackRouter);

  @override
  set router(_i2.RootStackRouter? _router) => super.noSuchMethod(
        Invocation.setter(
          #router,
          _router,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i2.StackedPage<dynamic>> get stack => (super.noSuchMethod(
        Invocation.getter(#stack),
        returnValue: <_i2.StackedPage<dynamic>>[],
        returnValueForMissingStub: <_i2.StackedPage<dynamic>>[],
      ) as List<_i2.StackedPage<dynamic>>);

  @override
  _i2.RouteData get topRoute => (super.noSuchMethod(
        Invocation.getter(#topRoute),
        returnValue: _FakeRouteData_1(
          this,
          Invocation.getter(#topRoute),
        ),
        returnValueForMissingStub: _FakeRouteData_1(
          this,
          Invocation.getter(#topRoute),
        ),
      ) as _i2.RouteData);

  @override
  dynamic setRouter(_i2.RootStackRouter? router) => super.noSuchMethod(
        Invocation.method(
          #setRouter,
          [router],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i18.Future<dynamic> navigateTo(
    _i2.PageRouteInfo<dynamic>? route, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [route],
          {#onFailure: onFailure},
        ),
        returnValue: _i18.Future<dynamic>.value(),
        returnValueForMissingStub: _i18.Future<dynamic>.value(),
      ) as _i18.Future<dynamic>);

  @override
  _i18.Future<void> navigateToPath({
    required String? path,
    bool? includePrefixMatches = false,
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToPath,
          [],
          {
            #path: path,
            #includePrefixMatches: includePrefixMatches,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  _i18.Future<T?> navigateWithTransition<T extends Object?>(
    _i19.Widget? widget, {
    _i19.RouteTransitionsBuilder? transitionBuilder,
    bool? fullscreenDialog = false,
    Duration? transitionDuration = const Duration(milliseconds: 300),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [widget],
          {
            #transitionBuilder: transitionBuilder,
            #fullscreenDialog: fullscreenDialog,
            #transitionDuration: transitionDuration,
          },
        ),
        returnValue: _i18.Future<T?>.value(),
        returnValueForMissingStub: _i18.Future<T?>.value(),
      ) as _i18.Future<T?>);

  @override
  _i18.Future<T?> replaceWith<T extends Object?>(
    _i2.PageRouteInfo<dynamic>? route, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [route],
          {#onFailure: onFailure},
        ),
        returnValue: _i18.Future<T?>.value(),
        returnValueForMissingStub: _i18.Future<T?>.value(),
      ) as _i18.Future<T?>);

  @override
  _i18.Future<void> clearStackAndShow(
    _i2.PageRouteInfo<dynamic>? route, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [route],
          {#onFailure: onFailure},
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  _i18.Future<void> clearStackAndShowView(
    _i19.Widget? widget, {
    _i19.RouteTransitionsBuilder? transitionBuilder,
    bool? fullscreenDialog = false,
    Duration? transitionDuration = const Duration(milliseconds: 300),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [widget],
          {
            #transitionBuilder: transitionBuilder,
            #fullscreenDialog: fullscreenDialog,
            #transitionDuration: transitionDuration,
          },
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  void popForced<T extends Object?>([T? result]) => super.noSuchMethod(
        Invocation.method(
          #popForced,
          [result],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i18.Future<bool> pop<T extends Object?>([T? result]) => (super.noSuchMethod(
        Invocation.method(
          #pop,
          [result],
        ),
        returnValue: _i18.Future<bool>.value(false),
        returnValueForMissingStub: _i18.Future<bool>.value(false),
      ) as _i18.Future<bool>);

  @override
  void back<T extends Object?>({T? result}) => super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {#result: result},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.RoutingController topMostRouter({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #topMostRouter,
          [],
          {#ignorePagelessRoutes: ignorePagelessRoutes},
        ),
        returnValue: _FakeRoutingController_2(
          this,
          Invocation.method(
            #topMostRouter,
            [],
            {#ignorePagelessRoutes: ignorePagelessRoutes},
          ),
        ),
        returnValueForMissingStub: _FakeRoutingController_2(
          this,
          Invocation.method(
            #topMostRouter,
            [],
            {#ignorePagelessRoutes: ignorePagelessRoutes},
          ),
        ),
      ) as _i2.RoutingController);

  @override
  _i18.Future<T?> pushNativeRoute<T extends Object?>(_i19.Route<T>? route) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNativeRoute,
          [route],
        ),
        returnValue: _i18.Future<T?>.value(),
        returnValueForMissingStub: _i18.Future<T?>.value(),
      ) as _i18.Future<T?>);
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock
    implements _i20.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i20.SheetBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #setCustomSheetBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i18.Future<_i21.SheetResponse<dynamic>?> showBottomSheet({
    required String? title,
    String? description,
    String? confirmButtonTitle = 'Ok',
    String? cancelButtonTitle,
    bool? enableDrag = true,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
    double? elevation = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [],
          {
            #title: title,
            #description: description,
            #confirmButtonTitle: confirmButtonTitle,
            #cancelButtonTitle: cancelButtonTitle,
            #enableDrag: enableDrag,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
            #elevation: elevation,
          },
        ),
        returnValue: _i18.Future<_i21.SheetResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i18.Future<_i21.SheetResponse<dynamic>?>.value(),
      ) as _i18.Future<_i21.SheetResponse<dynamic>?>);

  @override
  _i18.Future<_i21.SheetResponse<T>?> showCustomSheet<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i22.Color? barrierColor = const _i22.Color(2315255808),
    double? elevation = 1.0,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    String? barrierLabel = '',
    dynamic customData,
    R? data,
    bool? enableDrag = true,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomSheet,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #elevation: elevation,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
            #enableDrag: enableDrag,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i18.Future<_i21.SheetResponse<T>?>.value(),
        returnValueForMissingStub: _i18.Future<_i21.SheetResponse<T>?>.value(),
      ) as _i18.Future<_i21.SheetResponse<T>?>);

  @override
  void completeSheet(_i21.SheetResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeSheet,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i23.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i23.DialogBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i19.Widget Function(
      _i19.BuildContext,
      _i24.DialogRequest<dynamic>,
      dynamic Function(_i21.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i18.Future<_i21.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i22.Color? cancelTitleColor,
    String? buttonTitle = 'Ok',
    _i22.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i19.RouteSettings? routeSettings,
    _i19.GlobalKey<_i19.NavigatorState>? navigatorKey,
    _i23.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i18.Future<_i21.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i18.Future<_i21.DialogResponse<dynamic>?>.value(),
      ) as _i18.Future<_i21.DialogResponse<dynamic>?>);

  @override
  _i18.Future<_i21.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i22.Color? barrierColor = const _i22.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = '',
    bool? useSafeArea = true,
    _i19.RouteSettings? routeSettings,
    _i19.GlobalKey<_i19.NavigatorState>? navigatorKey,
    _i19.RouteTransitionsBuilder? transitionBuilder,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #useSafeArea: useSafeArea,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #transitionBuilder: transitionBuilder,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i18.Future<_i21.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i18.Future<_i21.DialogResponse<T>?>.value(),
      ) as _i18.Future<_i21.DialogResponse<T>?>);

  @override
  _i18.Future<_i21.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = 'Cancel',
    _i22.Color? cancelTitleColor,
    String? confirmationTitle = 'Ok',
    _i22.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i19.RouteSettings? routeSettings,
    _i23.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #confirmationTitle: confirmationTitle,
            #confirmationTitleColor: confirmationTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i18.Future<_i21.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i18.Future<_i21.DialogResponse<dynamic>?>.value(),
      ) as _i18.Future<_i21.DialogResponse<dynamic>?>);

  @override
  void completeDialog(_i21.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i25.ApiService {
  @override
  _i3.ApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakeApiClient_3(
          this,
          Invocation.getter(#apiClient),
        ),
        returnValueForMissingStub: _FakeApiClient_3(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i3.ApiClient);

  @override
  set apiClient(_i3.ApiClient? _apiClient) => super.noSuchMethod(
        Invocation.setter(
          #apiClient,
          _apiClient,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i18.Future<_i4.UserProfile> getDashboard({required String? username}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDashboard,
          [],
          {#username: username},
        ),
        returnValue: _i18.Future<_i4.UserProfile>.value(_FakeUserProfile_4(
          this,
          Invocation.method(
            #getDashboard,
            [],
            {#username: username},
          ),
        )),
        returnValueForMissingStub:
            _i18.Future<_i4.UserProfile>.value(_FakeUserProfile_4(
          this,
          Invocation.method(
            #getDashboard,
            [],
            {#username: username},
          ),
        )),
      ) as _i18.Future<_i4.UserProfile>);

  @override
  _i18.Future<_i5.PostResponse> postUserPoints({
    required String? username,
    required int? points,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUserPoints,
          [],
          {
            #username: username,
            #points: points,
          },
        ),
        returnValue: _i18.Future<_i5.PostResponse>.value(_FakePostResponse_5(
          this,
          Invocation.method(
            #postUserPoints,
            [],
            {
              #username: username,
              #points: points,
            },
          ),
        )),
        returnValueForMissingStub:
            _i18.Future<_i5.PostResponse>.value(_FakePostResponse_5(
          this,
          Invocation.method(
            #postUserPoints,
            [],
            {
              #username: username,
              #points: points,
            },
          ),
        )),
      ) as _i18.Future<_i5.PostResponse>);

  @override
  _i18.Future<_i6.UserPoints> getUserPoints({required String? username}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPoints,
          [],
          {#username: username},
        ),
        returnValue: _i18.Future<_i6.UserPoints>.value(_FakeUserPoints_6(
          this,
          Invocation.method(
            #getUserPoints,
            [],
            {#username: username},
          ),
        )),
        returnValueForMissingStub:
            _i18.Future<_i6.UserPoints>.value(_FakeUserPoints_6(
          this,
          Invocation.method(
            #getUserPoints,
            [],
            {#username: username},
          ),
        )),
      ) as _i18.Future<_i6.UserPoints>);

  @override
  _i18.Future<_i7.Leaderboard> getLeaderboard() => (super.noSuchMethod(
        Invocation.method(
          #getLeaderboard,
          [],
        ),
        returnValue: _i18.Future<_i7.Leaderboard>.value(_FakeLeaderboard_7(
          this,
          Invocation.method(
            #getLeaderboard,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i18.Future<_i7.Leaderboard>.value(_FakeLeaderboard_7(
          this,
          Invocation.method(
            #getLeaderboard,
            [],
          ),
        )),
      ) as _i18.Future<_i7.Leaderboard>);

  @override
  _i18.Future<_i8.UserRank> getUserRank({required String? username}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserRank,
          [],
          {#username: username},
        ),
        returnValue: _i18.Future<_i8.UserRank>.value(_FakeUserRank_8(
          this,
          Invocation.method(
            #getUserRank,
            [],
            {#username: username},
          ),
        )),
        returnValueForMissingStub:
            _i18.Future<_i8.UserRank>.value(_FakeUserRank_8(
          this,
          Invocation.method(
            #getUserRank,
            [],
            {#username: username},
          ),
        )),
      ) as _i18.Future<_i8.UserRank>);

  @override
  _i18.Future<_i5.PostResponse> postMarkTask({
    required String? username,
    required String? level,
    required String? assignmentType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postMarkTask,
          [],
          {
            #username: username,
            #level: level,
            #assignmentType: assignmentType,
          },
        ),
        returnValue: _i18.Future<_i5.PostResponse>.value(_FakePostResponse_5(
          this,
          Invocation.method(
            #postMarkTask,
            [],
            {
              #username: username,
              #level: level,
              #assignmentType: assignmentType,
            },
          ),
        )),
        returnValueForMissingStub:
            _i18.Future<_i5.PostResponse>.value(_FakePostResponse_5(
          this,
          Invocation.method(
            #postMarkTask,
            [],
            {
              #username: username,
              #level: level,
              #assignmentType: assignmentType,
            },
          ),
        )),
      ) as _i18.Future<_i5.PostResponse>);

  @override
  _i18.Future<_i5.PostResponse> postUserLevel({required String? username}) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUserLevel,
          [],
          {#username: username},
        ),
        returnValue: _i18.Future<_i5.PostResponse>.value(_FakePostResponse_5(
          this,
          Invocation.method(
            #postUserLevel,
            [],
            {#username: username},
          ),
        )),
        returnValueForMissingStub:
            _i18.Future<_i5.PostResponse>.value(_FakePostResponse_5(
          this,
          Invocation.method(
            #postUserLevel,
            [],
            {#username: username},
          ),
        )),
      ) as _i18.Future<_i5.PostResponse>);

  @override
  _i18.Future<_i9.AppConnections> getAppConnections(
          {required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppConnections,
          [],
          {#userId: userId},
        ),
        returnValue:
            _i18.Future<_i9.AppConnections>.value(_FakeAppConnections_9(
          this,
          Invocation.method(
            #getAppConnections,
            [],
            {#userId: userId},
          ),
        )),
        returnValueForMissingStub:
            _i18.Future<_i9.AppConnections>.value(_FakeAppConnections_9(
          this,
          Invocation.method(
            #getAppConnections,
            [],
            {#userId: userId},
          ),
        )),
      ) as _i18.Future<_i9.AppConnections>);

  @override
  _i18.Future<_i10.SignAuth> getAppAuthUrl({
    required String? appId,
    required String? userId,
    required String? urlEndPoint,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppAuthUrl,
          [],
          {
            #appId: appId,
            #userId: userId,
            #urlEndPoint: urlEndPoint,
          },
        ),
        returnValue: _i18.Future<_i10.SignAuth>.value(_FakeSignAuth_10(
          this,
          Invocation.method(
            #getAppAuthUrl,
            [],
            {
              #appId: appId,
              #userId: userId,
              #urlEndPoint: urlEndPoint,
            },
          ),
        )),
        returnValueForMissingStub:
            _i18.Future<_i10.SignAuth>.value(_FakeSignAuth_10(
          this,
          Invocation.method(
            #getAppAuthUrl,
            [],
            {
              #appId: appId,
              #userId: userId,
              #urlEndPoint: urlEndPoint,
            },
          ),
        )),
      ) as _i18.Future<_i10.SignAuth>);

  @override
  _i18.Future<_i11.GenerateTweet> postGenerateTweet({
    required String? userId,
    required String? topic,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postGenerateTweet,
          [],
          {
            #userId: userId,
            #topic: topic,
          },
        ),
        returnValue:
            _i18.Future<_i11.GenerateTweet>.value(_FakeGenerateTweet_11(
          this,
          Invocation.method(
            #postGenerateTweet,
            [],
            {
              #userId: userId,
              #topic: topic,
            },
          ),
        )),
        returnValueForMissingStub:
            _i18.Future<_i11.GenerateTweet>.value(_FakeGenerateTweet_11(
          this,
          Invocation.method(
            #postGenerateTweet,
            [],
            {
              #userId: userId,
              #topic: topic,
            },
          ),
        )),
      ) as _i18.Future<_i11.GenerateTweet>);

  @override
  _i18.Future<_i12.SaveGeneratedTweet> postSaveGeneratedTweet({
    required String? userId,
    required String? content,
    required String? tweetStatus,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postSaveGeneratedTweet,
          [],
          {
            #userId: userId,
            #content: content,
            #tweetStatus: tweetStatus,
          },
        ),
        returnValue: _i18.Future<_i12.SaveGeneratedTweet>.value(
            _FakeSaveGeneratedTweet_12(
          this,
          Invocation.method(
            #postSaveGeneratedTweet,
            [],
            {
              #userId: userId,
              #content: content,
              #tweetStatus: tweetStatus,
            },
          ),
        )),
        returnValueForMissingStub: _i18.Future<_i12.SaveGeneratedTweet>.value(
            _FakeSaveGeneratedTweet_12(
          this,
          Invocation.method(
            #postSaveGeneratedTweet,
            [],
            {
              #userId: userId,
              #content: content,
              #tweetStatus: tweetStatus,
            },
          ),
        )),
      ) as _i18.Future<_i12.SaveGeneratedTweet>);

  @override
  _i18.Future<_i13.Tweets> getTweets({
    required String? userId,
    required String? tweetStatus,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTweets,
          [],
          {
            #userId: userId,
            #tweetStatus: tweetStatus,
          },
        ),
        returnValue: _i18.Future<_i13.Tweets>.value(_FakeTweets_13(
          this,
          Invocation.method(
            #getTweets,
            [],
            {
              #userId: userId,
              #tweetStatus: tweetStatus,
            },
          ),
        )),
        returnValueForMissingStub:
            _i18.Future<_i13.Tweets>.value(_FakeTweets_13(
          this,
          Invocation.method(
            #getTweets,
            [],
            {
              #userId: userId,
              #tweetStatus: tweetStatus,
            },
          ),
        )),
      ) as _i18.Future<_i13.Tweets>);

  @override
  _i18.Future<_i12.SaveGeneratedTweet> postUpdateTweetStatus({
    required String? userId,
    required String? tweetId,
    required String? tweetStatus,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUpdateTweetStatus,
          [],
          {
            #userId: userId,
            #tweetId: tweetId,
            #tweetStatus: tweetStatus,
          },
        ),
        returnValue: _i18.Future<_i12.SaveGeneratedTweet>.value(
            _FakeSaveGeneratedTweet_12(
          this,
          Invocation.method(
            #postUpdateTweetStatus,
            [],
            {
              #userId: userId,
              #tweetId: tweetId,
              #tweetStatus: tweetStatus,
            },
          ),
        )),
        returnValueForMissingStub: _i18.Future<_i12.SaveGeneratedTweet>.value(
            _FakeSaveGeneratedTweet_12(
          this,
          Invocation.method(
            #postUpdateTweetStatus,
            [],
            {
              #userId: userId,
              #tweetId: tweetId,
              #tweetStatus: tweetStatus,
            },
          ),
        )),
      ) as _i18.Future<_i12.SaveGeneratedTweet>);

  @override
  _i18.Future<_i14.CryptoNews> getCryptoNews({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCryptoNews,
          [],
          {#userId: userId},
        ),
        returnValue: _i18.Future<_i14.CryptoNews>.value(_FakeCryptoNews_14(
          this,
          Invocation.method(
            #getCryptoNews,
            [],
            {#userId: userId},
          ),
        )),
        returnValueForMissingStub:
            _i18.Future<_i14.CryptoNews>.value(_FakeCryptoNews_14(
          this,
          Invocation.method(
            #getCryptoNews,
            [],
            {#userId: userId},
          ),
        )),
      ) as _i18.Future<_i14.CryptoNews>);

  @override
  _i18.Future<_i15.FetchUserPersonality> getUserPersonality(
          {required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPersonality,
          [],
          {#userId: userId},
        ),
        returnValue: _i18.Future<_i15.FetchUserPersonality>.value(
            _FakeFetchUserPersonality_15(
          this,
          Invocation.method(
            #getUserPersonality,
            [],
            {#userId: userId},
          ),
        )),
        returnValueForMissingStub: _i18.Future<_i15.FetchUserPersonality>.value(
            _FakeFetchUserPersonality_15(
          this,
          Invocation.method(
            #getUserPersonality,
            [],
            {#userId: userId},
          ),
        )),
      ) as _i18.Future<_i15.FetchUserPersonality>);

  @override
  _i18.Future<_i16.UpsertUserPersonality> postUserPersonality({
    required String? userId,
    required Map<String, double>? sliderValues,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUserPersonality,
          [],
          {
            #userId: userId,
            #sliderValues: sliderValues,
          },
        ),
        returnValue: _i18.Future<_i16.UpsertUserPersonality>.value(
            _FakeUpsertUserPersonality_16(
          this,
          Invocation.method(
            #postUserPersonality,
            [],
            {
              #userId: userId,
              #sliderValues: sliderValues,
            },
          ),
        )),
        returnValueForMissingStub:
            _i18.Future<_i16.UpsertUserPersonality>.value(
                _FakeUpsertUserPersonality_16(
          this,
          Invocation.method(
            #postUserPersonality,
            [],
            {
              #userId: userId,
              #sliderValues: sliderValues,
            },
          ),
        )),
      ) as _i18.Future<_i16.UpsertUserPersonality>);
}

/// A class which mocks [HiveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveService extends _i1.Mock implements _i26.HiveService {
  @override
  _i18.Future<void> storeData(
    String? boxName,
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeData,
          [
            boxName,
            key,
            value,
          ],
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  _i18.Future<dynamic> retrieveData(
    String? boxName,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrieveData,
          [
            boxName,
            key,
          ],
        ),
        returnValue: _i18.Future<dynamic>.value(),
        returnValueForMissingStub: _i18.Future<dynamic>.value(),
      ) as _i18.Future<dynamic>);

  @override
  _i18.Future<bool> containsKey(
    String? boxName,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [
            boxName,
            key,
          ],
        ),
        returnValue: _i18.Future<bool>.value(false),
        returnValueForMissingStub: _i18.Future<bool>.value(false),
      ) as _i18.Future<bool>);

  @override
  _i18.Future<void> closeAllBoxes() => (super.noSuchMethod(
        Invocation.method(
          #closeAllBoxes,
          [],
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);
}

/// A class which mocks [AuthorizationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthorizationService extends _i1.Mock
    implements _i27.AuthorizationService {
  @override
  set authWindow(_i27.WindowInstance? _authWindow) => super.noSuchMethod(
        Invocation.setter(
          #authWindow,
          _authWindow,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i18.Future<bool> authenticate(String? authUrl) => (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [authUrl],
        ),
        returnValue: _i18.Future<bool>.value(false),
        returnValueForMissingStub: _i18.Future<bool>.value(false),
      ) as _i18.Future<bool>);
}
